global:
  scrape_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node_exporter
    static_configs:
      - targets: ["localhost:9100"]
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['localhost:30080','localhost:30081']
  - job_name: 'kube-cadvisor'
    static_configs:
      - targets: ["localhost:10250"]
    scheme: https
    metrics_path: /metrics/cadvisor
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /home/user/monitor-token
