apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: exporter
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.14.0
  name: kube-state-metrics
  namespace: kube-system
spec:
  # clusterIP: None
  type: NodePort  # 将类型更改为 NodePort
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
    nodePort: 30080  # 指定要在每个节点上暴露的端口
  
  - name: telemetry
    port: 8081
    targetPort: telemetry
    nodePort: 30081  # 指定要在每个节点上暴露的端口
  
  selector:
    app.kubernetes.io/name: kube-state-metrics

